mpd:
    # mpd server network to connect
    network: "tcp"
    # mpd server address to connect
    addr: "localhost:6600"
    # set music_directory in mpd.conf value to search album cover image.
    music_directory: "/path/to/music/dir"

server:
    # this app serving address
    addr: ":8080"
