mpd:
    # mpd server network protocol to connect
    # default: tcp
    network: "tcp"
    # mpd server address to connect
    # default: localhost:6600
    addr: "localhost:6600"
    # set music_directory in mpd.conf value to search album cover image.
    # default: music_directory in mpd.conf if exists
    music_directory: "/path/to/music/dir"
    # mpd.conf path to get music_directory and http audio output.
    # default: /etc/mpd.conf
    conf: "/etc/mpd.conf"

server:
    # this app serving address
    # default: :8080
    addr: ":8080"
    # this app cache directory
    # default: https://golang.org/pkg/os/#TempDir + vv
    cache_directory: "/tmp/vv"
    cover:
      # search album cover image in mpd.music_directory
      # default: true
      local: true
      # search album cover image via mpd api
      # this feature uses server.cache_directory
      # default: false
      remote: true

playlist:
  tree:
    AlbumArtist:
      # song order tags
      sort: ["AlbumArtist", "Date", "Album", "DiscNumber", "TrackNumber", "Title", "file"]
      # defines playlist view:
      # left param: tag for grouping(must be defined in sort)
      # right param: view style(plain, album, song)
      tree:
      - ["AlbumArtist", "plain"]
      - ["Album", "album"]
      - ["Title", "song"]
    Album:
      # tags can be joined by "-"
      sort: ["Date-Album", "DiscNumber", "TrackNumber", "Title", "file"]
      tree: [["Date-Album", "album"], ["Title", "song"]]
    Artist:
      sort: ["Artist", "Date", "Album", "DiscNumber", "TrackNumber", "Title", "file"]
      tree: [["Artist", "plain"], ["Title", "song"]]
    Genre:
      sort: ["Genre", "Album", "DiscNumber", "TrackNumber", "Title", "file"]
      tree: [["Genre", "plain"], ["Album", "album"], ["Title", "song"]]
    Date:
      sort: ["Date", "Album", "DiscNumber", "TrackNumber", "Title", "file"]
      tree: [["Date", "plain"], ["Album", "album"], ["Title", "song"]]
    Composer:
      sort: ["Composer", "Date", "Album", "DiscNumber", "TrackNumber", "Title", "file"]
      tree: [["Composer", "plain"], ["Album", "album"], ["Title", "song"]]
    Performer:
      sort: ["Performer", "Date", "Album", "DiscNumber", "TrackNumber", "Title", "file"]
      tree: [["Performer", "plain"], ["Album", "album"], ["Title", "song"]]
  tree_order: ["AlbumArtist", "Album", "Artist", "Genre", "Date", "Composer", "Performer"]
