name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.16' ]
    name: Test Go ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: gofmt
      run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
    - name: golint
      run: test -z "$(go run golang.org/x/lint/golint ./... | tee /dev/stderr)"
    - name: go vet
      run: go vet ./...
    - name: go test
      run: go test ./... -v
    - name: go build
      run: make all
